### ISSUE TITLE
Fails or hangs when trying to load cached simfiles containing commas

### ISSUE THREAD

**Issue by DeadCakeTKL** [retronx-team/stepmania-nx#6] opened 2020-04-17 19:49 UTC
Official simfiles such as `Hello, planet` and `Help me, ERINNNNNN` from DDR A contain commas in their folder names. When Stepmania tries to load these cached simfiles, the program will indefinitely hang (I've only waited 10 minutes so I'm not sure if it eventually loads). Removing the commas from the folder names and clearing the cache of those songs lets the program load.

Samsung EVO Select 512 GB UHS Class U3 Class 10
EmuNAND 5.0.2
Atmosphere 0.10.5

**Comment by p-sam** [comment] 2021-05-03 22:00
I was doing an update since it was crashing for another reason, can you tell me if this still happens with the latest release ? (re-download needed to run on latest Atmosphère) I just tried with both in a folder and it loaded

**Comment by p-sam** [comment] 2021-05-06 19:56
I'll close this in the meantime seeing it now works here, feel free to ping me if you can reproduce the case

**Closed by p-sam** 2021-05-06 19:56 UTC
