### ISSUE TITLE
Crash on opening the nro

### ISSUE THREAD

**Issue by AM7999** [retronx-team/stepmania-nx#14] opened 2021-12-15 02:33 UTC
In app override whenever i try to run the stepmania nro the app crashes

**Comment by p-sam** [comment] 2021-12-18 14:36
Seems like a duplicate of #13, or a file corruption problem. Try to copy the files cleanly again from the latest release and check for the archive bit with hekate. Check the related issue for context, and ping me again with logs if this still doesnt work

**Closed as completed by p-sam** 2021-12-18 14:36 UTC
